const users = [
  {
    id: 1,
    name: "Abdulsalam Muhammed-Jamiu",
    // state: "Kogi state",
    // age: 37,
    image: "/photo.png",
    email: "anatemuhammed@gmail.com",
    gender: "Male",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum natus, necessitatibus et deserunt animi magnam libero ducimus ipsam, accusantium suscipit, id laboriosam labore esse aliquam aperiam at nam ipsa Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fuga error quam quae recusandae libero distinctio animi sit deleniti officiis, iste hic sunt corrupti consectetur dolore. Placeat magnam quam totam voluptatem!",
  },
  {
    id: 2,
    name: "Aka'aba Musa",
    // age: 47,
    // state: "Kogi state",
    image: "/musa.jpg",
    email: "aka'abamusa@gmail.com",
    gender: "Male",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum natus, necessitatibus et deserunt animi magnam libero ducimus ipsam, accusantium suscipit, id laboriosam labore esse aliquam aperiam at nam ipsa Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fuga error quam quae recusandae libero distinctio animi sit deleniti officiis, iste hic sunt corrupti consectetur dolore. Placeat magnam quam totam voluptatem!",
  },
  {
    id: 3,
    name: "Mrs fronshal",
    age: 57,
    state: "Kogi state",
    image: "/member-01.jpg",
    email: "mrsfronshal@gmail.com",
    gender: "Male",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum natus, necessitatibus et deserunt animi magnam libero ducimus ipsam, accusantium suscipit, id laboriosam labore esse aliquam aperiam at nam ipsa Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fuga error quam quae recusandae libero distinctio animi sit deleniti officiis, iste hic sunt corrupti consectetur dolore. Placeat magnam quam totam voluptatem!",
  },
  {
    id: 4,
    name: "Mrs lateshal shu",
    age: 27,
    state: "Kogi state",
    image: "/member-02.jpg",
    email: "mrslateshalshu@gmail.com",
    gender: "Male",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum natus, necessitatibus et deserunt animi magnam libero ducimus ipsam, accusantium suscipit, id laboriosam labore esse aliquam aperiam at nam ipsa,Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fuga error quam quae recusandae libero distinctio animi sit deleniti officiis, iste hic sunt corrupti consectetur dolore. Placeat magnam quam totam voluptatem!",
  },
  {
    id: 5,
    name: "Anate Abdulrahim",
    age: 30,
    state: "Kogi state",
    image: "/senbro.jpg",
    email: "anateabdulrahim@gmail.com",
    gender: "Male",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum natus, necessitatibus et deserunt animi magnam libero ducimus ipsam, accusantium suscipit, id laboriosam labore esse aliquam aperiam at nam ipsa Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fuga error quam quae recusandae libero distinctio animi sit deleniti officiis, iste hic sunt corrupti consectetur dolore. Placeat magnam quam totam voluptatem!",
  },
  {
    id: 6,
    name: "Mr Tobi",
    age: 58,
    state: "Abuja",
    image: "/sirtobi.jpg",
    email: "sirtobi@gmail.com",
    gender: "Male",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum natus, necessitatibus et deserunt animi magnam libero ducimus ipsam, accusantium suscipit, id laboriosam labore esse aliquam aperiam at nam ipsa Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fuga error quam quae recusandae libero distinctio animi sit deleniti officiis, iste hic sunt corrupti consectetur dolore. Placeat magnam quam totam voluptatem!",
  },

  {
    id: 8,
    name: "Mr Blatasha",
    age: 58,
    state: "Abuja",
    image: "/member-03.jpg",
    email: "mrBlatasha@gmail.com",
    gender: "Male",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum natus, necessitatibus et deserunt animi magnam libero ducimus ipsam, accusantium suscipit, id laboriosam labore esse aliquam aperiam at nam ipsa Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fuga error quam quae recusandae libero distinctio animi sit deleniti officiis, iste hic sunt corrupti consectetur dolore. Placeat magnam quam totam voluptatem!",
  },
];
export default users;
